spring.application.name=blog

spring.datasource.url=jdbc:postgresql://localhost:5432/blog
spring.datasource.username=derek
spring.datasource.password=blog
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
