CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_app_user PRIMARY KEY (id)
);

CREATE TABLE post (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id BIGINT,
    title VARCHAR(255),
    body VARCHAR(255),
    slug VARCHAR(255) NOT NULL,
    CONSTRAINT pk_post PRIMARY KEY (id),
    CONSTRAINT uk_post_slug UNIQUE (slug),
    CONSTRAINT fk_post_user FOREIGN KEY (user_id) REFERENCES app_user (id)
);
